[annotation]
id = "GHSA-vjv6-gq77-3mjw"
date = "2020-07-24"
repository = "https://github.com/mapfish/mapfish-print"
package = "pkg:maven/org.mapfish.print/print-lib"
categories = ["file-disclosure"]
keywords = ["XXE"]
cwe = "611"
related = [
    "https://github.com/mapfish/mapfish-print/commit/e1d0527d13db06b2b62ca7d6afb9e97dacd67a0e",
    "https://github.com/mapfish/mapfish-print/pull/1397",
]
exploits = ""

[annotation.related_packages]
"pkg:maven/org.mapfish.print/print-servlet" = "< 3.24"
"pkg:maven/org.mapfish.print/print-standalone" = "< 3.24"
[affected.functions]
"org.mapfish.print.map.style::SLDParserPlugin::tryLoadSLD" = ["< 3.24"]
"org.mapfish.print.servlet::MapPrinterServlet::getStatusSpecificAppId" = ["< 3.24"]
"org.mapfish.print.servlet::MapPrinterServlet::getStatus" = ["< 3.24"]
"org.mapfish.print.servlet::MapPrinterServlet::listAppIds" = ["< 3.24"]
"org.mapfish.print.servlet::MapPrinterServlet::getCapabilities" = ["< 3.24"]
"org.mapfish.print.servlet::MapPrinterServlet::getExampleRequest" = ["< 3.24"]

[versions]
patched = [">= 3.24"]
