[annotation]
id = "GHSA-9h4g-27m8-qjrg"
related_ids = ["NPM-1519"]
date = "2020-07-25"
repository = "https://github.com/rico345100/socket.io-file"
package = "pkg:npm/socket.io-file"
categories = ["file-disclosure"]
keywords = ["path-traversal", "websockets", "sanitization"]
cwe = "22"
related = ["https://github.com/rico345100/socket.io-file/blob/master/index.js#L87-L89"]
exploits = ""

[affected.functions]
"socket.io-file::SocketIOFile::socket.on('socket.io-file::createFile')" = ["< 2.0.31"]
