[annotation]
id = "GHSA-mm44-wc5p-wqhq"
date = "2020-07-24"
repository = "https://github.com/peteroupc/cbor-java"
package = "pkg:maven/com.upokecenter/cbor"
categories = ["denial-of-service"]
keywords = ["reference-expansion", "serialization"]
cwe = "400"
related = ["https://github.com/kubernetes/kubernetes/issues/83253"]
exploits = ""

[affected.functions]
"com.upokecenter.cbor::CBORObject::DecodeFromBytes" = ["< 4.0.0"]
"com.upokecenter.cbor::CBORObject::EncodeToBytes" = ["< 4.0.0"]
"com.upokecenter.cbor::CBORObject::ToString" = ["< 4.0.0"]
"com.upokecenter.cbor::CBORObject::ToJSONString" = ["< 4.0.0"]

[versions]
patched = [">= 4.0.0"]
