annotation]
id = "GHSA-wvh7-5p38-2qfc"
date = "2020-07-24"
repository = "https://github.com/parse-community/Parse-SDK-JS"
package = "pkg:npm/parse"
categories = ["crypto-failure"]
keywords = [
    "password",
    "localStorage",
]
cwe = "400"
related = [
    "http://parseplatform.org/Parse-SDK-JS/api/2.9.1/Parse.User.html#setPassword",
    "https://github.com/parse-community/Parse-SDK-JS/commit/d1106174571b699f972929dd7cbb8e45b5283cbb",
]
exploits = ""
[affected.functions]
"::ParseUser::setPassword" = ["< 2.10.0"]
"::ParseUser::DefaultController.updateUserOnDisk" = ["< 2.10.0"]

[versions]
patched = [">= 2.10.0"]
