[annotation]
id = "NPM-1540"
date = "2020-07-24"
repository = "https://github.com/SAP/cloud-sdk"
package = "pkg:npm/@sap-cloud-sdk/core"
categories = ["privilege-escalation"]
keywords = ["authorization", "JWT"]
cwe = "285"
related = ["https://github.com/SAP/cloud-sdk/blob/b087a3778fe93af9d5dc11dba772a9c41905b693/CHANGELOG.md#fixed-issues-4"]
exploits = ""

[affected.functions]
"util::jwt::verifyJwt" = ["< 1.21.2"]
"util::jwt::verifyJwtWithKey" = ["< 1.21.2"]
"util::jwt::fetchAndCacheKeyAndVerify" = ["< 1.21.2"]

[versions]
patched = [">= 1.21.2"]
